Repository nextflow-io/nextflow, pull requests merged in 2024-07, with the labels that each got.

#5098 Add retry options to Azure Blob client
  plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
  plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzHelperTest.groovy
Labels: storage/azure

#5114 Fix normalization of consecutive slashes in uri path
  modules/nf-commons/src/main/nextflow/file/FileHelper.groovy
  modules/nf-commons/src/test/nextflow/file/FileHelperTest.groovy
  plugins/nf-amazon/src/test/nextflow/file/FileHelperS3Test.groovy
  plugins/nf-azure/src/test/nextflow/file/FileHelperAzTest.groovy
  plugins/nf-google/src/main/nextflow/cloud/google/util/GsPathFactory.groovy
  plugins/nf-google/src/test/nextflow/file/FileHelperGsTest.groovy
Labels: backport/24.04.3

#5146 Fix aws logs group name
  docs/config.md
Labels: backport/24.04.4

#5177 More robust parsing of shm-size containerOptions
  plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsContainerOptionsMapper.groovy
  plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsContainerOptionsMapperTest.groovy
Labels: backport/24.04.4

#5160 Apply k8s.cpuLimits to kuberun driver pod
  modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy
  modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy
Labels: executor/k8s

#5170 Add runtime error for missing channel factory
  modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionProvider.groovy
  modules/nextflow/src/test/groovy/nextflow/script/ScriptDslTest.groovy
Labels: error-improvements

#3395 remove capsule dependencies
  Makefile
  VERSION
  docs/config.md
  modules/nextflow/build.gradle
  modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
  nextflow
  packing.gradle
Labels: software/java
